### ISSUE TITLE
Using the po folder

### ISSUE THREAD

**Issue by sabriunal** [dlippok/photometric-viewer#90]
Hi, while it's not a rule, many GNOME apps use the /po folder to store and manage translations. For example:

 - Nautilus: https://gitlab.gnome.org/GNOME/nautilus/-/tree/main/po?ref_type=heads
- GNOME Shell: https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/po?ref_type=heads

I believe following this convention may be better for translators.

Thanks.

**Comment by dlippok** [comment]
Hello and thanks a lot making me aware of it. I really appreciate that you took the time and had a look at the project from the perspective of a translator. However currently this is only a one-man pet project of mine and I can only put limited resources into it. In order to avoid distraction from the development tasks and discussions about personal taste I decided from the beginning not to accept any suggestions for improvements that do not affect the end users of the software. This includes even small changes like the setup of the repository, project structure, code style, etc.
